sudo: true

language: cpp

services:
  - docker

before_install:
  - wget https://raw.githubusercontent.com/tue-robotics/tue-env/master/ci/install-package.sh
  - wget https://raw.githubusercontent.com/tue-robotics/tue-env/master/ci/build-package.sh
  - export PACKAGE=${TRAVIS_REPO_SLUG#*/}
  - 'if [[ $TRAVIS_PULL_REQUEST == "true" ]]; 
     then
         COMMIT=$TRAVIS_PULL_REQUEST_SHA;
     else
         COMMIT=$TRAVIS_COMMIT;
     fi'
  - echo $TRAVIS_PULL_REQUEST_SHA

install:
  - bash install-package.sh --package=$PACKAGE --branch=$TRAVIS_BRANCH --commit=$TRAVIS_COMMIT 

script: 
  - bash build-package.sh --package=$PACKAGE
