sudo: true

language: cpp

services:
  - docker

before_install:
  - wget https://raw.githubusercontent.com/tue-robotics/tue-env/feature/docker-image-use-scripts/ci/install-package.sh
  - wget https://raw.githubusercontent.com/tue-robotics/tue-env/feature/docker-image-use-scripts/ci/build-package.sh
  - export PACKAGE=${TRAVIS_REPO_SLUG#*/}
  - echo $PACKAGE

install:
  - bash install-package.sh --package=$PACKAGE --branch=$TRAVIS_BRANCH --commit=$TRAVIS_COMMIT 

script: 
  - bash build-package.sh --package=$PACKAGE --branch=$TRAVIS_BRANCH --commit=$TRAVIS_COMMIT 
