sudo: true

language: cpp

compiler:
  - g++

services:
  - docker

before_install:
  - docker pull ubuntu:16.04
  - docker run -it ubuntu bash

install:
  - apt-get update
  - apt-get install lsb-release

script: "lsb_release"
