sudo: true

language: cpp

services:
  - docker

before_install:
  - export IMAGE_BRANCH_NAME=tuerobotics/tue-env:`echo "$TRAVIS_BRANCH" | tr '[:upper:]' '[:lower:]' | sed -e 's:/:_:g'`
  - export IMAGE_MASTER_NAME=tuerobotics/tue-env:master
  - export REPO_NAME=${TRAVIS_REPO_SLUG#*/}
  # Use master if identical branch does not exist
  - docker run --detach --interactive --name tue-env $IMAGE_BRANCH_NAME || docker run --detach --interactive --name tue-env $IMAGE_MASTER_NAME 

install:
  - docker exec tue-env bash -c "export CI='true'; source /home/amigo/.bashrc; tue-get install ros-$REPO_NAME"
  - docker exec tue-env bash -c "cd ~/ros/kinetic/system/src/$REPO_NAME"
  - docker exec tue-env bash -c "git reset --hard $TRAVIS_COMMIT"

script: 
  - docker exec tue-env bash -c "export CI='true'; source /home/amigo/.bashrc; catkin build --this --no-status"
